set_property PACKAGE_PIN L16 [get_ports sys_clk]
set_property PACKAGE_PIN R19 [get_ports v_sync]
set_property PACKAGE_PIN F19 [get_ports {r[2]}]
set_property PACKAGE_PIN G20 [get_ports {r[1]}]
set_property PACKAGE_PIN J20 [get_ports {r[0]}]
set_property PACKAGE_PIN G19 [get_ports {b[1]}]
set_property PACKAGE_PIN J18 [get_ports {b[0]}]
set_property PACKAGE_PIN F20 [get_ports {g[2]}]
set_property PACKAGE_PIN H20 [get_ports {g[1]}]
set_property PACKAGE_PIN J19 [get_ports {g[0]}]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN Y16 [get_ports game_action_button]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports game_action_button]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]

set_property IOSTANDARD LVCMOS33 [get_ports rota]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports rotb]
set_property IOSTANDARD LVCMOS33 [get_ports shoot_button]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]


set_property PACKAGE_PIN P16 [get_ports shoot_button]
